DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON (
     id MEDIUMINT NOT NULL AUTO_INCREMENT,
     fName CHAR(30) NOT NULL,
     lName CHAR(30) NOT NULL,
     phone CHAR(8) NOT NULL,
     PRIMARY KEY(id)
);

INSERT INTO PERSON (FNAME, LNAME, PHONE, ID)
    VALUES ('Simon', 'Steinaa', '22891305', 1);

INSERT INTO PERSON (FNAME, LNAME, PHONE, ID)
    VALUES ('Ib', 'Routhe', '11223344', 2);
